default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: library_db      # Заменено на имя вашей базы данных
  username: postgres    # Имя пользователя для подключения
  password: 7222802ma           # Пароль, который вы указали
  host: localhost           # Хост, если база данных локально

test:
  <<: *default
  database: library_test
  username: library_user
  password: admin
  host: localhost

production:
  primary: &primary_production
    <<: *default
    database: library_db_production    # Заменено на имя базы данных для production
    username: library_user             # Пользователь для production
    password: <%= ENV["LIBRARYBACK_DATABASE_PASSWORD"] %>
    host: localhost

  cache:
    <<: *primary_production
    database: library_db_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: library_db_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: library_db_production_cable
    migrations_paths: db/cable_migrate
